after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
before_script:
  - gem install bundler
  - bin/rails db:create
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
dist: trusty
env:
  global:
    - CC_TEST_REPORTER_ID=90ef038a13b4a7dcc89b1757386da91cfa4fb0e8968408998517d232e2c7f334
language: ruby
notifications:
  - false
rvm:
  - 2.5.0
script:
  - bundle exec rspec spec
  - bundle exec rails db:migrate RAILS_ENV=test
services:
  - postgresql: "10.3"
