development:
  adapter: postgresql
  encoding: unicode
  database: yelp_development
  pool: 5


test:
  adapter: postgresql
  encoding: unicode
  database: yelp_development
  pool: 5


production:
  adapter: postgresql
  encoding: unicode
  database: yelp_prod
  pool: 5
